# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_auto_20151209_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='add_as_hidden',
            field=models.BooleanField(default=False, verbose_name='Add as hidden'),
        ),
    ]
