# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0022_auto_20160517_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', related_name='gallery_tags', to='viewer.Tag'),
        ),
    ]
