# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0024_auto_20170116_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
