# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0025_auto_20170116_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='filesize',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='filesize',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Size'),
        ),
    ]
