# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_auto_20170117_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='announce',
            name='thumbnail_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announce',
            name='thumbnail_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='thumbnail_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='thumbnail_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='thumbnail_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='thumbnail_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announce',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', max_length=500, null=True, upload_to=viewer.models.upload_announce_thumb_handler, width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='thumbnail',
            field=models.ImageField(default='', height_field='thumbnail_height', max_length=500, upload_to=viewer.models.thumb_path_handler, width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(default='', height_field='thumbnail_height', max_length=500, upload_to=viewer.models.gallery_thumb_path_handler, width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', max_length=500, null=True, upload_to=viewer.models.upload_thumbpath_handler, width_field='thumbnail_width'),
        ),
    ]
