# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0027_auto_20170329_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('last_run', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='last run')),
            ],
        ),
    ]
