# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0028_scheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
