# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_auto_20170418_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantedgallery',
            name='matched_gallery',
        ),
    ]
