# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0030_remove_wantedgallery_matched_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='public_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
