# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0033_wantedgallery_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='source_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Source type'),
        ),
    ]
