# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0034_auto_20170712_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Provider'),
        ),
    ]
