# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0035_wantedgallery_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='notify_when_found',
            field=models.BooleanField(default=True, verbose_name='Notify when found'),
        ),
    ]
