# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0038_auto_20170720_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='expunged',
            field=models.BooleanField(default=False),
        ),
    ]
