# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0039_auto_20170722_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='dl_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
