# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0041_auto_20170728_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='unwanted_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wantedgallery',
            name='wanted_page_count_higher',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='wantedgallery',
            name='wanted_page_count_lower',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='archive',
            name='filecount',
            field=models.IntegerField(blank=True, null=True, verbose_name='File count'),
        ),
    ]
