# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0043_auto_20170729_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User friendly name', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('home_page', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('float', 'Float'), ('int', 'Integer'), ('date', 'Date'), ('duration', 'Duration'), ('bool', 'Boolean')], max_length=10)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('value_duration', models.DurationField(blank=True, null=True)),
                ('value_bool', models.NullBooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Provider')),
            ],
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='providerattribute',
            unique_together={('name', 'provider')},
        ),
    ]
