# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0045_auto_20170806_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerattribute',
            options={'verbose_name_plural': 'Provider attributes'},
        ),
    ]
