# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0047_auto_20170806_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
