# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0049_auto_20170806_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
