# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0050_wantedgallery_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Normal'), (5, 'Deleted')], db_index=True, default=1),
        ),
    ]
