# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0051_gallery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
