# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0052_wantedgallery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='wanted_tags_exclusive_scope',
            field=models.BooleanField(default=False),
        ),
    ]
