# Generated by Django 2.0 on 2017-12-12 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0053_wantedgallery_wanted_tags_exclusive_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
