# Generated by Django 2.1 on 2018-08-06 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0055_auto_20180805_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Gallery'),
        ),
    ]
