# Generated by Django 2.1 on 2018-08-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0056_gallery_gallery_container'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'permissions': (('publish_archive', 'Can publish available archives'), ('upload_with_metadata_archive', 'Can upload a file with an associated metadata source'))},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'permissions': (('publish_gallery', 'Can publish available galleries'), ('approve_gallery', 'Can approve submitted galleries')), 'verbose_name_plural': 'galleries'},
        ),
    ]
