# Generated by Django 2.1 on 2018-08-14 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0061_auto_20180811_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'permissions': (('publish_gallery', 'Can publish available galleries'), ('approve_gallery', 'Can approve submitted galleries'), ('crawler_adder', 'Can add links to the crawler with more options')), 'verbose_name_plural': 'galleries'},
        ),
    ]
