# Generated by Django 2.1 on 2018-08-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0063_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='data',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='result',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
