# Generated by Django 2.1 on 2018-08-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0064_auto_20180815_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'permissions': (('publish_archive', 'Can publish available archives'), ('match_archive', 'Can match archives'), ('upload_with_metadata_archive', 'Can upload a file with an associated metadata source'))},
        ),
    ]
