# Generated by Django 2.1 on 2018-09-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0065_auto_20180822_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'permissions': (('publish_gallery', 'Can publish available galleries'), ('approve_gallery', 'Can approve submitted galleries'), ('wanted_gallery_found', 'Can be notified of new wanted gallery matches'), ('crawler_adder', 'Can add links to the crawler with more options')), 'verbose_name_plural': 'galleries'},
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_wanted_gallery_found',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
