# Generated by Django 2.1 on 2018-10-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0066_auto_20180903_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wantedgallery',
            options={'ordering': ['-release_date'], 'permissions': (('view_wanted_gallery', 'Can view wanted galleries'), ('create_wanted_gallery', 'Can create wanted galleries'), ('edit_wanted_gallery', 'Can edit wanted galleries')), 'verbose_name_plural': 'Wanted galleries'},
        ),
    ]
