# Generated by Django 2.1 on 2018-12-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0070_auto_20181003_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='alternative_sources',
            field=models.ManyToManyField(blank=True, default='', related_name='alternative_sources', to='viewer.Gallery'),
        ),
    ]
