# Generated by Django 2.1.4 on 2018-12-10 17:20

from django.db import migrations, models
import viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0071_archive_alternative_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='zipped',
            field=models.FileField(max_length=500, storage=viewer.models.OriginalFilenameFileSystemStorage(), upload_to=viewer.models.archive_path_handler, verbose_name='File'),
        ),
    ]
