# Generated by Django 2.1.7 on 2019-04-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0073_auto_20190105_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='reason',
            field=models.CharField(blank=True, default='backup', max_length=200, null=True),
        ),
    ]
