# Generated by Django 2.2 on 2019-04-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0077_auto_20190418_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='wanted_providers',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Providers'),
        ),
    ]
