# Generated by Django 2.2.1 on 2019-05-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0078_wantedgallery_wanted_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='original_filename',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Original Filename'),
        ),
    ]
