# Generated by Django 2.2.3 on 2019-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0082_auto_20190712_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivegroup',
            name='archives',
            field=models.ManyToManyField(blank=True, default='', related_name='archive_groups', through='viewer.ArchiveGroupEntry', to='viewer.Archive'),
        ),
    ]
