# Generated by Django 2.2.6 on 2019-12-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0084_auto_20190729_1516'),
    ]

    operations = [
        migrations.RenameModel('Announce', 'Mention')
    ]

    atomic = False
