# Generated by Django 2.2.6 on 2019-12-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0085_auto_20191218_2100'),
    ]

    operations = [
        migrations.RenameField('Mention', 'announce_date', 'mention_date'),
        migrations.RenameField('WantedGallery', 'announces', 'mentions'),
    ]
