# Generated by Django 2.2.6 on 2019-12-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0086_auto_20191218_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='mention_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mention date'),
        ),
    ]
