# Generated by Django 3.0.1 on 2019-12-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0087_auto_20191218_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
    ]
