# Generated by Django 3.0.7 on 2020-08-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0091_auto_20200805_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='provider',
            field=models.CharField(default='generic', max_length=50, verbose_name='Provider'),
        ),
    ]
