# Generated by Django 3.0.7 on 2020-08-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0092_auto_20200806_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='unwanted_providers',
            field=models.ManyToManyField(blank=True, related_name='unwanted_providers', to='viewer.Provider'),
        ),
    ]
