# Generated by Django 3.1.2 on 2020-10-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0093_wantedgallery_unwanted_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Normal'), (4, 'Denied'), (5, 'Deleted'), (6, 'No metadata')], db_index=True, default=1),
        ),
    ]
