# Generated by Django 3.1.5 on 2021-01-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0094_auto_20201006_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazine_chapters', to='viewer.gallery'),
        ),
    ]
