# Generated by Django 3.1.7 on 2021-03-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0096_gallerysubmitentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerysubmitentry',
            options={'verbose_name_plural': 'Gallery submit entries'},
        ),
    ]
