# Generated by Django 3.1.7 on 2021-03-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0098_auto_20210309_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'permissions': (('publish_gallery', 'Can publish available galleries'), ('view_submitted_gallery', 'Can view submitted galleries'), ('approve_gallery', 'Can approve submitted galleries'), ('wanted_gallery_found', 'Can be notified of new wanted gallery matches'), ('crawler_adder', 'Can add links to the crawler with more options')), 'verbose_name_plural': 'galleries'},
        ),
    ]
