# Generated by Django 3.2 on 2021-04-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0100_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='wait_for_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Wait for time'),
        ),
    ]
