# Generated by Django 3.2 on 2021-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0101_wantedgallery_wait_for_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='exclusive_scope_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
