# Generated by Django 3.2 on 2021-04-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0102_wantedgallery_exclusive_scope_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantedgallery',
            name='look_for_duration',
        ),
    ]
