# Generated by Django 3.2 on 2021-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0103_remove_wantedgallery_look_for_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='wanted_tags_accept_if_none_scope',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
