# Generated by Django 3.2 on 2021-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0104_wantedgallery_wanted_tags_accept_if_none_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='data',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
