# Generated by Django 3.2.2 on 2021-05-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0106_alter_archive_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'permissions': (('publish_archive', 'Can publish available archives'), ('manage_archive', 'Can manage available archives'), ('match_archive', 'Can match archives'), ('update_metadata', 'Can update metadata'), ('recalc_fileinfo', 'Can recalculate file info'), ('upload_with_metadata_archive', 'Can upload a file with an associated metadata source'), ('expand_archive', 'Can extract and reduce archives'))},
        ),
    ]
