# Generated by Django 3.2.4 on 2021-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0108_wantedgallery_add_to_archive_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysubmitentry',
            name='similar_galleries',
            field=models.ManyToManyField(blank=True, default='', related_name='_viewer_gallerysubmitentry_similar_galleries_+', to='viewer.Gallery'),
        ),
    ]
