# Generated by Django 3.2.4 on 2021-06-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0109_gallerysubmitentry_similar_galleries'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userarchiveprefs',
            constraint=models.UniqueConstraint(fields=('user', 'archive'), name='unique_user_archive'),
        ),
    ]
