# Generated by Django 3.2.5 on 2021-08-05 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0110_userarchiveprefs_unique_user_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveManageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_check', models.BooleanField(default=False)),
                ('mark_priority', models.FloatField(blank=True, default=1.0, null=True)),
                ('mark_reason', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mark_comment', models.TextField(blank=True, default='', null=True)),
                ('mark_result', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('resolve_check', models.BooleanField(default=False)),
                ('resolve_comment', models.TextField(blank=True, default='', null=True)),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.archive')),
                ('mark_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_entry_mark', to=settings.AUTH_USER_MODEL)),
                ('resolve_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_entry_resolver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Archive manage entries',
            },
        ),
    ]
