# Generated by Django 3.2.5 on 2021-08-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0111_archivemanageentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivemanageentry',
            name='archive',
        ),
    ]
