# Generated by Django 3.2.5 on 2021-08-05 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0112_remove_archivemanageentry_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivemanageentry',
            name='id',
        ),
        migrations.AddField(
            model_name='archivemanageentry',
            name='archive',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='viewer.archive'),
            preserve_default=False,
        ),
    ]
