# Generated by Django 3.2.5 on 2021-08-16 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0115_alter_eventlog_options'),
    ]

    operations = [
        migrations.DeleteModel('archivemanageentry')
    ]
