# Generated by Django 3.2.5 on 2021-08-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0117_archivemanageentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivemanageentry',
            options={'ordering': ['mark_priority'], 'verbose_name_plural': 'Archive manage entries'},
        ),
    ]
