# Generated by Django 3.2.5 on 2021-08-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0119_archivemanageentry_mark_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivemanageentry',
            name='mark_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='archivemanageentry',
            name='mark_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
