# Generated by Django 3.2.5 on 2021-08-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0120_auto_20210816_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivemanageentry',
            name='mark_extra',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
