# Generated by Django 3.2.6 on 2021-08-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0123_archive_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='origin',
            field=models.SmallIntegerField(choices=[(1, 'Default'), (2, 'Accept Submitted'), (3, 'Add URL'), (4, 'Upload Archive'), (5, 'Wanted Gallery'), (6, 'Folder Scan')], db_index=True, default=1),
        ),
    ]
