# Generated by Django 3.2.6 on 2021-08-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0125_remove_wantedgallery_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivemanageentry',
            options={'ordering': ['-mark_priority'], 'verbose_name_plural': 'Archive manage entries'},
        ),
    ]
