# Generated by Django 3.2.7 on 2021-09-05 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0128_alter_archivemanageentry_resolve_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('read_private_stats', 'Can check the general statistics about the backup'),)},
        ),
    ]
