# Generated by Django 3.2.7 on 2021-09-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0129_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantedgallery',
            name='add_as_hidden',
        ),
    ]
