# Generated by Django 3.2.7 on 2021-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0130_remove_wantedgallery_add_as_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivemanageentry',
            name='origin',
            field=models.SmallIntegerField(choices=[(1, 'System'), (2, 'User')], db_index=True, default=1),
        ),
    ]
