# Generated by Django 3.2.7 on 2021-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0131_archivemanageentry_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivemanageentry',
            name='origin',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'System'), (2, 'User')], db_index=True, default=1),
        ),
    ]
