# Generated by Django 3.2.7 on 2021-09-19 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0133_alter_gallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2000)),
                ('description', models.TextField(blank=True, default='')),
                ('proxy', models.CharField(blank=True, max_length=200, null=True)),
                ('stop_page', models.IntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('auto_start', models.BooleanField(default=False)),
                ('frequency', models.DurationField()),
                ('create_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.provider')),
            ],
            options={
                'verbose_name_plural': 'Monitored Links',
                'ordering': ['-create_date'],
            },
        ),
    ]
