# Generated by Django 3.2.7 on 2021-09-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0135_monitoredlink_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredlink',
            options={'ordering': ['-create_date'], 'permissions': (('view_monitored_links', 'Can view a general view of all monitored links'),), 'verbose_name_plural': 'Monitored Links'},
        ),
    ]
