# Generated by Django 3.2.11 on 2022-03-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0137_alter_archive_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='regexp_search_title_icase',
            field=models.BooleanField(blank=True, default=False, verbose_name='Regexp search title case-insensitive'),
        ),
        migrations.AddField(
            model_name='wantedgallery',
            name='regexp_unwanted_title_icase',
            field=models.BooleanField(blank=True, default=False, verbose_name='Regexp unwanted title case-insensitive'),
        ),
    ]
