# Generated by Django 3.2.13 on 2022-05-20 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0138_auto_20220330_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'permissions': (('publish_archive', 'Can publish available archives'), ('manage_archive', 'Can manage available archives'), ('mark_archive', 'Can mark available archives'), ('view_marks', 'Can view archive marks'), ('match_archive', 'Can match archives'), ('update_metadata', 'Can update metadata'), ('recalc_fileinfo', 'Can recalculate file info'), ('upload_with_metadata_archive', 'Can upload a file with an associated metadata source'), ('expand_archive', 'Can extract and reduce archives'), ('compare_archives', 'Can compare archives based on different algorithms'), ('recycle_archive', 'Can utilize the Archive Recycle Bin'), ('archive_internal_info', 'Can see selected internal Archive information'))},
        ),
        migrations.CreateModel(
            name='ArchiveRecycleEntry',
            fields=[
                ('archive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recycle_entry', serialize=False, to='viewer.archive')),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.TextField(blank=True, default='')),
                ('date_deleted', models.DateTimeField(default=django.utils.timezone.now)),
                ('origin', models.SmallIntegerField(blank=True, choices=[(1, 'System'), (2, 'User')], db_index=True, default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_recycle_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Archive recycle entries',
                'ordering': ['-date_deleted'],
            },
        ),
    ]
