# Generated by Django 3.2.13 on 2022-05-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0139_auto_20220519_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'permissions': (('publish_archive', 'Can publish available archives'), ('manage_archive', 'Can manage available archives'), ('mark_archive', 'Can mark available archives'), ('view_marks', 'Can view archive marks'), ('match_archive', 'Can match archives'), ('update_metadata', 'Can update metadata'), ('recalc_fileinfo', 'Can recalculate file info'), ('upload_with_metadata_archive', 'Can upload a file with an associated metadata source'), ('expand_archive', 'Can extract and reduce archives'), ('compare_archives', 'Can compare archives based on different algorithms'), ('recycle_archive', 'Can utilize the Archive Recycle Bin'), ('archive_internal_info', 'Can see selected internal Archive information'), ('mark_similar_archive', 'Can run the similar Archives process'))},
        ),
    ]
