# Generated by Django 3.2.13 on 2022-05-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0140_alter_archive_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='binned',
            field=models.BooleanField(default=False),
        ),
    ]
