# Generated by Django 3.2.13 on 2022-06-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0145_auto_20220606_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryproviderdata',
            name='origin',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Native'), (2, 'Processed'), (3, 'Other')], db_index=True, default=3),
        ),
    ]
