# Generated by Django 4.0.5 on 2022-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0147_auto_20220607_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerysubmitentry',
            name='similar_galleries',
            field=models.ManyToManyField(blank=True, default='', related_name='+', to='viewer.gallery'),
        ),
    ]
