# Generated by Django 4.0.6 on 2022-07-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0148_alter_gallerysubmitentry_similar_galleries'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='provider_metadata',
            field=models.TextField(blank=True, default=''),
        ),
    ]
