# Generated by Django 4.0.8 on 2022-11-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0149_gallery_provider_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='data',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
