# Generated by Django 4.1.5 on 2023-01-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0151_image_image_format_image_image_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
