# Generated by Django 4.1.5 on 2023-01-27 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0154_historicalgallery_alter_archive_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalarchive',
            name='original_filename',
        ),
    ]
