# Generated by Django 4.1.5 on 2023-01-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0156_archive_archive_binned_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgallery',
            name='provider',
        ),
    ]
