# Generated by Django 4.1.5 on 2023-01-31 22:46

from django.db import migrations, models
import django.db.models.deletion


def move_tags(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Archive = apps.get_model('viewer', 'Archive')
    ArchiveTag = apps.get_model('viewer', 'ArchiveTag')
    for archive in Archive.objects.all():
        archive.new_tags.set(archive.tags.all())
        for tag in archive.custom_tags.all():
            archive_tag = ArchiveTag(archive=archive, tag=tag, origin=2)
            archive_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0159_alter_eventlog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.SmallIntegerField(blank=True, choices=[(1, 'System'), (2, 'User')], db_index=True, default=1)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.archive')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.tag')),
            ],
            options={
                'verbose_name_plural': 'Archive Tags',
                'ordering': ['-origin'],
            },
        ),
        migrations.AddField(
            model_name='archive',
            name='new_tags',
            field=models.ManyToManyField(blank=True, related_name='archive_tags', through='viewer.ArchiveTag', to='viewer.tag'),
        ),
        migrations.RunPython(move_tags),
        migrations.RemoveField(
            model_name='archive',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='custom_tags',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='new_tags',
            new_name='tags',
        ),
    ]
