# Generated by Django 4.2.1 on 2023-05-31 21:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0163_alter_tag_unique_together_tag_unique_scope_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLongLivedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=256, unique=True)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2033, 5, 28, 21, 53, 21, 69625, tzinfo=datetime.timezone.utc))),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_lived_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='viewer_user_name_f0c4c8_idx'), models.Index(fields=['key'], name='viewer_user_key_7094e0_idx')],
            },
        ),
    ]
