# Generated by Django 4.2.1 on 2023-06-01 22:15

from django.db import migrations, models
import viewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0164_userlonglivedtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('read_private_stats', 'Can check the general statistics about the backup'), ('use_remote_api', 'Can use the remote admin API'))},
        ),
        migrations.AlterField(
            model_name='userlonglivedtoken',
            name='expire_date',
            field=models.DateTimeField(default=viewer.models.in_10_years),
        ),
    ]
