# Generated by Django 4.2.3 on 2023-07-18 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0165_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=200, unique=True, verbose_name='Source Id')),
                ('url', models.URLField(max_length=2000)),
                ('link_date', models.DateTimeField(blank=True, null=True, verbose_name='Link date')),
                ('content', models.TextField(blank=True, default='')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.provider')),
            ],
            options={
                'verbose_name_plural': 'Processed Links',
            },
        ),
    ]
