# Generated by Django 4.2.3 on 2023-07-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0166_processedlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedlinks',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
