# Generated by Django 4.2.4 on 2023-08-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0167_processedlinks_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveSizeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Priority')),
                ('file_type', models.CharField(blank=True, default='', max_length=40, verbose_name='File Type')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.archive')),
            ],
            options={
                'verbose_name_plural': 'Archive size entries',
                'ordering': ['-priority'],
            },
        ),
    ]
