# Generated by Django 4.2.6 on 2023-10-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0169_archivefileentry_delete_archivesizeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeze_titles', models.BooleanField(blank=True, default=False)),
                ('freeze_tags', models.BooleanField(blank=True, default=False)),
                ('archive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='viewer.archive')),
            ],
        ),
    ]
