# Generated by Django 5.0.3 on 2024-03-26 03:34

import django.core.validators
import viewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0170_archiveoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='image_height', max_length=500, upload_to=viewer.models.upload_wanted_image_handler, width_field='image_width')),
                ('active', models.BooleanField(default=False)),
                ('image_name', models.CharField(blank=True, max_length=500, null=True)),
                ('image_height', models.PositiveIntegerField(null=True)),
                ('image_width', models.PositiveIntegerField(null=True)),
                ('image_format', models.CharField(blank=True, max_length=50, null=True)),
                ('image_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('image_size', models.PositiveIntegerField(null=True)),
                ('thumbnail_height', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_width', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, height_field='thumbnail_height', max_length=500, null=True, upload_to=viewer.models.upload_wanted_image_thumbnail_handler, width_field='thumbnail_width')),
                ('sha1', models.CharField(blank=True, max_length=50, null=True)),
                ('match_threshold', models.FloatField(default=0.8, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
                ('match_method', models.CharField(choices=[('cv.TM_CCOEFF', 'TM_CCOEFF'), ('cv.TM_CCOEFF_NORMED', 'TM_CCOEFF_NORMED'), ('cv.TM_CCORR', 'TM_CCORR'), ('cv.TM_CCORR_NORMED', 'TM_CCORR_NORMED'), ('cv.TM_SQDIFF', 'TM_SQDIFF'), ('cv.TM_SQDIFF_NORMED', 'TM_SQDIFF_NORMED')], db_index=True, default='cv.TM_CCOEFF_NORMED')),
            ],
        ),
    ]
