# Generated by Django 5.0.3 on 2024-03-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0171_wantedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedimage',
            name='match_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wantedimage',
            name='match_width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
