# Generated by Django 5.0.3 on 2024-03-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0172_wantedimage_match_height_wantedimage_match_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedimage',
            name='match_method',
            field=models.CharField(choices=[('TM_CCOEFF', 'TM_CCOEFF'), ('TM_CCOEFF_NORMED', 'TM_CCOEFF_NORMED'), ('TM_CCORR', 'TM_CCORR'), ('TM_CCORR_NORMED', 'TM_CCORR_NORMED'), ('TM_SQDIFF', 'TM_SQDIFF'), ('TM_SQDIFF_NORMED', 'TM_SQDIFF_NORMED')], db_index=True, default='TM_CCOEFF_NORMED'),
        ),
    ]
