# Generated by Django 5.0.3 on 2024-03-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0173_alter_wantedimage_match_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
