# Generated by Django 5.0.3 on 2024-03-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0174_alter_wantedimage_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedimage',
            name='mark_priority',
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AlterField(
            model_name='wantedimage',
            name='match_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wantedimage',
            name='match_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
