# Generated by Django 5.0.3 on 2024-03-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0175_wantedimage_mark_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wantedimage',
            name='match_method',
        ),
        migrations.AddField(
            model_name='wantedimage',
            name='minimum_features',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
