# Generated by Django 5.0.4 on 2024-04-16 03:10

import django.db.models.deletion
import viewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0178_gallery_disowned_historicalgallery_disowned'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundWantedImageOnArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('result_image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('result_image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('result_image', models.ImageField(blank=True, height_field='result_image_height', max_length=500, null=True, upload_to=viewer.models.upload_found_wanted_image_thumbnail_handler, width_field='result_image_width')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.archive')),
                ('wanted_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.wantedimage')),
            ],
        ),
    ]
