# Generated by Django 5.0.4 on 2024-04-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0179_foundwantedimageonarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedimage',
            name='restrict_by_homogeneity',
            field=models.BooleanField(default=False),
        ),
    ]
