# Generated by Django 5.0.4 on 2024-04-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0180_wantedimage_restrict_by_homogeneity'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysubmitentry',
            name='submit_group',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
