# Generated by Django 5.0.4 on 2024-04-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0181_gallerysubmitentry_submit_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('progress', models.FloatField(default=0.0)),
                ('total_size', models.PositiveIntegerField(default=0)),
                ('failed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('method', models.CharField()),
                ('agent', models.CharField()),
                ('download_id', models.CharField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Posted date')),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.archive')),
            ],
        ),
    ]
