# Generated by Django 5.0.4 on 2024-04-26 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0182_downloadevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadevent',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.gallery'),
        ),
    ]
