# Generated by Django 5.0.6 on 2024-06-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0186_alter_image_image_height_alter_image_image_width'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['sha1'], name='image_sha1'),
        ),
    ]
