# Generated by Django 5.1.4 on 2024-12-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0189_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
