# Generated by Django 5.1.7 on 2025-03-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0190_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="file_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalarchive",
            name="file_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
