# Generated by Django 5.1.7 on 2025-04-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0191_archive_file_deleted_historicalarchive_file_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveStatistics",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("filesize_average", models.FloatField(blank=True, null=True)),
                ("height_mode", models.PositiveIntegerField(blank=True, null=True)),
                ("width_mode", models.PositiveIntegerField(blank=True, null=True)),
                ("height_average", models.FloatField(blank=True, null=True)),
                ("width_average", models.FloatField(blank=True, null=True)),
                ("image_mode_mode", models.CharField(blank=True, max_length=50, null=True)),
                ("is_horizontal_mode", models.BooleanField(default=False)),
                ("archive", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="viewer.archive")),
            ],
            options={
                "verbose_name_plural": "Archive file statistics",
            },
        ),
    ]
