# Generated by Django 5.1.7 on 2025-04-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0192_archivestatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivestatistics",
            name="file_type_mode",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
