# Generated by Django 5.1.7 on 2025-04-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0193_archivestatistics_file_type_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivestatistics",
            name="height_stddev",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="archivestatistics",
            name="width_stddev",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
