# Generated by Django 5.1.7 on 2025-04-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0194_archivestatistics_height_stddev_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivestatistics",
            name="file_type_match",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
