# Generated by Django 5.2 on 2025-04-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0195_archivestatistics_file_type_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="possible_matches",
            field=models.ManyToManyField(
                blank=True,
                default="",
                related_name="possible_matches",
                through="viewer.ArchiveMatches",
                through_fields=("archive", "gallery"),
                to="viewer.gallery",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="archive_tags",
                through="viewer.ArchiveTag",
                through_fields=("archive", "tag"),
                to="viewer.tag",
            ),
        ),
        migrations.AlterField(
            model_name="archivegroup",
            name="archives",
            field=models.ManyToManyField(
                blank=True,
                default="",
                related_name="archive_groups",
                through="viewer.ArchiveGroupEntry",
                through_fields=("archive_group", "archive"),
                to="viewer.archive",
            ),
        ),
        migrations.AlterField(
            model_name="wantedgallery",
            name="found_galleries",
            field=models.ManyToManyField(
                blank=True,
                related_name="found_galleries",
                through="viewer.FoundGallery",
                through_fields=("wanted_gallery", "gallery"),
                to="viewer.gallery",
            ),
        ),
        migrations.AlterField(
            model_name="wantedgallery",
            name="possible_matches",
            field=models.ManyToManyField(
                blank=True,
                related_name="gallery_matches",
                through="viewer.GalleryMatch",
                through_fields=("wanted_gallery", "gallery"),
                to="viewer.gallery",
            ),
        ),
    ]
