# Generated by Django 5.2 on 2025-05-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0196_alter_archive_possible_matches_alter_archive_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryMatchGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GalleryMatchGroupEntry",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gallery_position", models.PositiveIntegerField(default=1)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True, null=True)),
                ("gallery", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="viewer.gallery")),
                (
                    "gallery_match_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="viewer.gallerymatchgroup"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gallerymatchgroup",
            name="galleries",
            field=models.ManyToManyField(
                blank=True,
                default="",
                related_name="gallery_group",
                through="viewer.GalleryMatchGroupEntry",
                through_fields=("gallery_match_group", "gallery"),
                to="viewer.gallery",
            ),
        ),
    ]
