# Generated by Django 5.2 on 2025-05-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0197_gallerymatchgroup_gallerymatchgroupentry_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallerymatchgroupentry",
            options={"verbose_name_plural": "Gallery match group entries"},
        ),
    ]
