# Generated by Django 5.2 on 2025-05-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0199_alter_gallerymatchgroupentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerymatchgroup",
            name="title",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
