# Generated by Django 5.2.3 on 2025-06-15 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0200_gallerymatchgroup_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryGroupPossibleMatches",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "match_type",
                    models.CharField(blank=True, default="", max_length=40, null=True, verbose_name="Match type"),
                ),
                (
                    "match_accuracy",
                    models.FloatField(blank=True, default=0.0, null=True, verbose_name="Match accuracy"),
                ),
                ("gallery", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="viewer.gallery")),
                (
                    "gallery_match_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="viewer.gallerymatchgroup"),
                ),
            ],
            options={
                "verbose_name_plural": "Gallery group possible matches",
                "ordering": ["-match_accuracy"],
            },
        ),
        migrations.AddField(
            model_name="gallerymatchgroup",
            name="possible_matches",
            field=models.ManyToManyField(
                blank=True,
                default="",
                related_name="possible_match_group_matches",
                through="viewer.GalleryGroupPossibleMatches",
                through_fields=("gallery_match_group", "gallery"),
                to="viewer.gallery",
            ),
        ),
    ]
