# Generated by Django 5.2.3 on 2025-06-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0202_alter_archive_options_archivemanageentry_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivemanageentry",
            name="status",
            field=models.SmallIntegerField(choices=[(1, "Normal"), (5, "Not Indexed")], db_index=True, default=1),
        ),
    ]
