# Generated by Django 5.2.8 on 2025-11-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0203_alter_archivemanageentry_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(models.OrderBy(models.F('create_date'), descending=True, nulls_last=True), models.OrderBy(models.F('public'), nulls_last=True), models.F('status'), name='gallery_pub_norm_create_date'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(models.OrderBy(models.F('posted'), descending=True, nulls_last=True), models.OrderBy(models.F('public'), nulls_last=True), models.F('status'), name='gallery_pub_norm_pub_date'),
        ),
    ]
