# Generated by Django 6.0.1 on 2026-02-06 13:02

from django.db import migrations, models


def add_index(apps, schema_editor):
    StatusLog = apps.get_model('django_db_logger', 'StatusLog')

    index = models.Index(
        fields=['-create_datetime'],
        name='statuslog_create_dt_idx'
    )

    schema_editor.add_index(StatusLog, index)


def remove_index(apps, schema_editor):
    StatusLog = apps.get_model('django_db_logger', 'StatusLog')
    index = models.Index(
        fields=['-create_datetime'],
        name='statuslog_create_dt_idx'
    )
    schema_editor.remove_index(StatusLog, index)


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0204_gallery_gallery_pub_norm_create_date_and_more'),
        ('django_db_logger', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_index, reverse_code=remove_index),
    ]
