# Generated by Django 6.0.2 on 2026-02-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0205_auto_20260206_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='match_expression',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
