# Generated by Django 6.0.2 on 2026-02-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0206_wantedgallery_match_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantedgallery',
            name='backlog_url_query',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
