# Generated by Django 6.0.2 on 2026-02-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0207_wantedgallery_backlog_url_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadevent',
            name='total_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
