#!/bin/sh
#
# PROVIDE: pandabackup
# REQUIRE: LOGIN
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable pandabackup:
# pandabackup_enable:         Set to NO by default. Set it to YES to enable it.
#
# pandabackup_user:           The user account PandaBackup daemon runs as what
#                       you want it to be.
# pandabackup_server_run:     Entry Python script full path.
#                           
# pandabackup_conf_dir:       Directory where PandaBackup configuration files live.
#
# pandabackup_python:         Python Executable location.
#

. /etc/rc.subr

name=pandabackup
rcvar=pandabackup_enable

load_rc_config $name
: ${pandabackup_enable:=no}
: ${pandabackup_user:=panda}
: ${pandabackup_server_run:=/home/panda/pandabackup/server.py}
: ${pandabackup_conf_dir:=/home/panda/pandabackup/}
: ${pandabackup_python:=python3.6}

pidfile="${pandabackup_conf_dir}${name}.pid"

command="${pandabackup_server_run}"
command_interpreter="${pandabackup_python}"

pandabackup_flags="-c ${pandabackup_conf_dir} -pf ${pidfile} -d"

sig_reload="USR2"

run_rc_command "$1"
