# Generated by Django 6.1.1 on 2026-10-01 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProcess',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, default='', max_length=150)),
                ('worker_type', models.CharField(default='general', max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_heartbeat', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(default='running', max_length=20)),
            ],
            options={
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(db_index=True, default='web_crawler', max_length=50)),
                ('args', models.JSONField(default=list, help_text='Command line arguments or URLs for the task.')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Serialized override options.')),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('event_action', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.IntegerField(db_index=True, default=10, help_text='Lower value means higher priority.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('worker_pid', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='workers_tas_status_7b6505_idx')],
            },
        ),
    ]
