# Generated by Django 6.1.1 on 2026-10-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerState',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('schedule_type', models.CharField(default='scheduler', max_length=50)),
                ('is_running', models.BooleanField(db_index=True, default=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('cycle_timer', models.FloatField(default=0.0)),
                ('worker_pid', models.IntegerField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('command_requested', models.CharField(blank=True, default='', max_length=50)),
                ('command_arg', models.CharField(blank=True, default='', max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
